version: '3.8'

services:
  web-dev:
    profiles: ["dev"]
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT=3000

  web-prod:
    profiles: ["prod"]
    build: 
      context: .
      target: prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
